feat/13 ERD 기반 도메인 클래스 구현 완료
hansung-PreCaps/Backend pull request #14
Opened 2024-10-17 07:54 UTC by rokaf6444

## PR 타입(하나 이상의 PR 타입을 선택해주세요)

- [x] 🚀 Feature

## 반영 브랜치
feat/13 -> develop

## 변경 사항
엔티티 생성 및 엔티티 간 관계 설정 추가했습니다.

## 테스트 실행

- [ ] 👍 Yes
- [x] 🙅 No, Because they are not neaded
- [ ] 🤯 No, Because I needed help with writing tests

### 테스트 결과

2024-10-17 09:17 UTC, lsh1215 commented on src/main/java/com/pictalk/global/domain/Group.java
> +    private Boolean isDeleted = false;
BaseEntity를 사용하고 extend하면 코드를 줄일 수 있을거 같아

2024-10-17 09:17 UTC, lsh1215 commented on src/main/java/com/pictalk/global/domain/Group.java
> +@Setter
Setter는 사실 잘 안쓰고, getter도 줄일려고 노력하는게 좋아.
우테코 클린코드 pr 문서 참고

2024-10-17 09:17 UTC, lsh1215 commented on src/main/java/com/pictalk/global/domain/Group.java
> +    private Long groupId;
변수명은 groupId일 필요가 있을까?
예를 들어 group.getGroupId라고 하면 난 좀 이상하게 느껴져서

2024-10-17 09:44 UTC, Enble requested changes
고생했습니다만 개선 여지가 있어 보입니다. 다음은 제 리뷰입니다.
추가적으로 모든 엔티티가 global의 domain 패키지에 작성되어 있는데, 이전의 페어 프로그래밍에서 정한 바 대로, 각 도메인을 적절히 별도의 패키지로 분리하는 작업이 필요해 보입니다.

2024-10-17 09:44 UTC, Enble commented on src/main/java/com/pictalk/global/domain/Group.java
> +@Table(name = "group")
깜빡하고 말 안했는데, group은 SQL 예약어라서 groups로 변경해서 작업해주세요

2024-10-17 09:44 UTC, Enble commented on src/main/java/com/pictalk/global/domain/Group.java
> +    private Long groupId;
동의합니다. 변수명은 단순히 id인 편이 나은 것 같아요

2024-10-17 09:44 UTC, Enble commented on src/main/java/com/pictalk/global/domain/Group.java
> +    @GeneratedValue
strategy를 명시적으로 지정해주는게 좋습니다.

2024-10-17 09:44 UTC, Enble commented on src/main/java/com/pictalk/global/domain/Message.java
> +    private MessageStatus status; // [SCHEDULED, SENT, CANCELLED]
enum를 필드로 사용할 때 다음을 고려해보면 좋습니다.
- `@Enumerated(EnumType.STRING)` 사용
- Attribute Converter 고려

2024-10-17 09:44 UTC, Enble commented on src/main/java/com/pictalk/global/domain/Receiver.java
> +    private Boolean isDeleted;
`isDeleted`가 Wrapper타입을 사용해야 하는지 생각해보셨나요? 의견을 듣고 싶습니다.

2024-10-18 04:44 UTC, rokaf6444 commented on src/main/java/com/pictalk/global/domain/Group.java
> +}
Applied what made sense, and kept the rest as is!

2024-10-18 05:09 UTC, rokaf6444 commented on src/main/java/com/pictalk/global/domain/Image.java
> +}
Applied what made sense, and kept the rest as is!

2024-10-18 05:21 UTC, rokaf6444 commented on src/main/java/com/pictalk/global/domain/Message.java
> +}
Applied what made sense, and kept the rest as is!

2024-10-18 05:24 UTC, rokaf6444 commented on src/main/java/com/pictalk/global/domain/MessageStatus.java
> +}
Applied what made sense, and kept the rest as is!

2024-10-18 05:27 UTC, rokaf6444 commented on src/main/java/com/pictalk/global/domain/Receiver.java
> +}
Applied what made sense, and kept the rest as is!

2024-10-18 05:40 UTC, rokaf6444 commented on src/main/java/com/pictalk/global/domain/Group.java
> +    private Long groupId;
Addressed your feedback!

2024-10-18 05:43 UTC, rokaf6444 commented on src/main/java/com/pictalk/global/domain/Group.java
> +@Table(name = "group")
피드백 반영했어요!

2024-10-18 05:44 UTC, rokaf6444 commented on src/main/java/com/pictalk/global/domain/Group.java
> +    @GeneratedValue
피드백 반영했어요!

2024-10-18 05:48 UTC, rokaf6444 commented on src/main/java/com/pictalk/global/domain/Receiver.java
> +    private Boolean isDeleted;
방금 기본 타입이 있다는 걸 알게 돼서 바로 반영했어요!

2024-10-18 06:04 UTC, rokaf6444 commented on src/main/java/com/pictalk/global/domain/Message.java
> +    private MessageStatus status; // [SCHEDULED, SENT, CANCELLED]
피드백 감사합니다! Message 클래스에서 MessageStatus 필드에 @Enumerated(EnumType.STRING)을 사용하도록 수정하였고, 이제 enum 값이 데이터베이스에 문자열로 저장됩니다.

2024-10-18 06:13 UTC, rokaf6444 commented on src/main/java/com/pictalk/global/domain/Group.java
> +    private Boolean isDeleted = false;
리뷰해 주신 부분은 다른 문제로 인해 수정했습니다. 다음에 유사한 상황에서는 BaseEntity를 활용해 보겠습니다!

2024-10-18 06:44 UTC, rokaf6444 commented on src/main/java/com/pictalk/global/domain/Group.java
> +@Setter
리뷰 감사드립니다! Setter와 Getter 사용에 대한 피드백에 동의합니다. 이번 이슈가 끝나면 코드 전체를 리팩토링하여 Setter를 제거하고 Getter도 최소화해 캡슐화를 강화하겠습니다!

2024-10-18 07:23 UTC, closed without merging