feat/13 ERD 기반 도메인 클래스 수정
hansung-PreCaps/Backend pull request #17
Opened 2024-10-18 10:44 UTC by rokaf6444

## PR 타입

- [ ] 🚀 Feature

## 반영 브랜치
feat/13 -> develop

## 변경 사항
feat/13의 피드백을 반영하여 도메인 클래스를 수정하였습니다. 주요 변경 사항은 다음과 같습니다:

- 패키지 구조를 개선했습니다.
- 필드 순서를 재배치했습니다.
- @GeneratedValue 전략을 명시적으로 설정했습니다.
- isDeleted 필드의 타입을 Boolean에서 boolean으로 변경했습니다.
- SQL 예약어와 충돌하는 테이블명을 수정했습니다.
- 객체 생성 시 createdAt 필드에 현재 시간이 자동으로 설정되도록 수정했습니다.

## 테스트 실행

- [ ] 👍 Yes
- [x] 🙅 No, Because they are not neaded
- [ ] 🤯 No, Because I needed help with writing tests

### 테스트 결과

2024-10-18 11:37 UTC, Enble requested changes
잘 수정하셨지만, 추가적인 수정 내용을 리뷰해드립니다.

추가로, 패키지 구성에 대한 제 설명이 부족했던 것 같아 추가적으로 설명하겠습니다.
현재 패키지는 아래와 같이 구성되어 있습니다.
- pictalk
  * global
    - domain
      * group
      * image
      * message

제가 의도한 패키지 구성은 다음과 같습니다.
- pictalk
  * global
  * group
    - domain
  * image
    - domain
  * message
    - domain

위 내용도 함께 수정해주세요!

2024-10-18 11:37 UTC, Enble commented on src/main/java/com/pictalk/global/domain/group/Group.java
> +@Setter
모든 Entity에서의 setter를 제거해주세요. 이유는 다음 글을 참고해보시면 좋겠습니다.
https://velog.io/@langoustine/setter-%EC%A7%80%EC%96%91-%EC%9D%B4%EC%9C%A0

2024-10-18 11:37 UTC, Enble commented on src/main/java/com/pictalk/global/domain/group/Group.java
> +@Setter
setter를 제거한 것과 같은 이유로 `@Builder`를 추가해주세요.

2024-10-18 11:37 UTC, Enble commented on src/main/java/com/pictalk/global/domain/group/Group.java
> +    private List<GroupReceiver> groupReceivers = new ArrayList<>();
빌더 패턴을 사용할 시 필드의 초기화가 builder를 통해 진행됩니다.
따라서 다음 글을 읽고 `@Builder.Default`를 고려해보는 건 어떨까요?
https://bbeomgeun.tistory.com/174#%--Builder-Default

2024-10-18 11:37 UTC, Enble commented on src/main/java/com/pictalk/global/domain/group/GroupReceiver.java
> +    private Long groupReceiverId;
모든 Entity에서의 id 필드를 정확히 `id`로 수정해주세요

2024-10-18 11:37 UTC, Enble commented on src/main/java/com/pictalk/global/domain/group/Group.java
> +    @Column(name = "groupId", nullable = false)
컬럼 네임은 snake_case로 작성해야 합니다. 주의해주세용

2024-10-18 12:56 UTC, rokaf6444 commented
49223955b394dc02886a77ea221d5cd9ab8b3f55: 피드백 반영하여 패키지 구성을 변경했습니다.

2024-10-18 13:19 UTC, rokaf6444 commented on src/main/java/com/pictalk/global/domain/group/Group.java
> +    @Column(name = "groupId", nullable = false)
감사합니다. 꼼꼼히 확인하겠습니다!

2024-10-18 13:33 UTC, rokaf6444 commented
b6f643033fd006bf7e350c1f8bdaf4b4af9b9a08: 컬럼 네임 snake_case 오류 수정 및 ID 필드명 통일하였습니다.

2024-10-18 13:43 UTC, rokaf6444 commented on src/main/java/com/pictalk/global/domain/group/GroupReceiver.java
> +    private Long groupReceiverId;
수정했습니다!

2024-10-22 02:42 UTC, rokaf6444 commented on src/main/java/com/pictalk/global/domain/group/Group.java
> +@Setter
확인했습니다.

2024-10-22 02:43 UTC, rokaf6444 commented on src/main/java/com/pictalk/global/domain/group/Group.java
> +    private List<GroupReceiver> groupReceivers = new ArrayList<>();
확인했습니다.

2024-10-22 02:43 UTC, rokaf6444 commented on src/main/java/com/pictalk/global/domain/group/Group.java
> +@Setter
확인했습니다.

2024-10-22 04:09 UTC, rokaf6444 commented
098a0f13d1d579ad4e50bd430720de0720273bd7: 엔티티의 Setter를 제거했습니다.

2024-10-22 04:22 UTC, Enble approved these changes
LGTM

2024-10-22 04:35 UTC, merged