feat/11
hansung-PreCaps/Backend pull request #20
Opened 2024-10-27 12:37 UTC by lsh1215

## PR 타입(하나 이상의 PR 타입을 선택해주세요)

- [ ] 🚀 Feature
- [ ] 🧹 Refactor
- [ ] 🛠️ Bug Fix
- [ ] 🧭 chore
- [ ] 🎨 design
- [ ] 🤖 perf
- [ ] 📁 test
- [ ] 📝 Documentation Update

## 변경 사항
jwt를 이용한 로그인 기능 구현

## 테스트 실행

- [ ] 👍 Yes
- [ ] 🙅 No, Because they are not neaded
- [ ] 🤯 No, Because I needed help with writing tests

### 테스트 결과
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.

2024-10-28 06:55 UTC, Enble requested changes
잘 하셨습니다. 리뷰 드릴게요.

추가적으로 yaml 파일 환경변수 처리 부탁드립니다.

2024-10-28 06:55 UTC, Enble commented on src/main/java/com/pictalk/global/config/SecurityConfig.java
> +                .authorizeHttpRequests(authorize -> authorize
다음의 설정도 추가 바랍니다.
```
.formLogin(AbstractHttpConfigurer::disable)
.logout(AbstractHttpConfigurer::disable)
```

2024-10-28 06:55 UTC, Enble commented on src/main/java/com/pictalk/global/config/SecurityConfig.java
> +//                .authorizeHttpRequests(requests ->
불필요한 주석을 삭제해주세요

2024-10-28 06:55 UTC, Enble commented on src/main/java/com/pictalk/global/jwt/JwtRequestFilter.java
> +    public String reIssueRefreshToken(User user) {
반환값이 사용되지 않는 경우에는 void로 처리해주세요

2024-10-28 06:55 UTC, Enble commented on src/main/java/com/pictalk/global/jwt/JwtToken.java
> +public class JwtToken {
안쓰는 DTO는 삭제하거나, 추후에 사용하도록 변경해주세요

2024-10-28 06:55 UTC, Enble commented on src/main/java/com/pictalk/global/payload/status/ErrorStatus.java
> +    USER_EMAIL_NOT_MATCH(HttpStatus.BAD_REQUEST, "USER_400", "이메일이 일치하지 않습니다."),
`code` 멤버가 동일하게 되지 않도록, "USER_4001", "USER_4002"와 같이 바꿔주세요

2024-10-28 06:55 UTC, Enble commented on src/main/java/com/pictalk/user/controller/UserController.java
> +        return ResponseEntity.status(201).body(response);
CommonResponse를 직접 리턴하도록 수정해주세요

2024-10-28 06:55 UTC, Enble commented on src/main/java/com/pictalk/user/converter/UserConverter.java
> +
UserConverter는 전부 static 메서드만 있으므로 private 생성자로 객체 생성을 막으면 좋을 것 같아요

2024-10-28 06:55 UTC, Enble commented on src/main/java/com/pictalk/user/domain/User.java
> -    private List<Sender> senders = new ArrayList<>();
sender에 대한 one to many 연관관계를 넣어주세요

2024-10-28 06:55 UTC, Enble commented on src/main/java/com/pictalk/user/domain/User.java
> -    private boolean isDeleted = false;
deleted 여부를 판별할 수 있는 메서드를 만들어주세요

2024-10-28 06:55 UTC, Enble commented on src/main/java/com/pictalk/user/domain/dto/UserRequestDto.java
> +//    @Builder
불필요한 주석 제거 요망

2024-10-28 06:55 UTC, Enble commented on src/main/java/com/pictalk/user/service/UserService.java
> +    // 로그인
`@Transactional` 걸어주세요

2024-10-28 06:55 UTC, Enble commented on src/main/java/com/pictalk/user/service/UserService.java
> +    // 로그아웃
`@Transactional` 걸어주세요

2024-10-29 07:08 UTC, lsh1215 commented
[131dc0a](https://github.com/hansung-PreCaps/Backend/pull/20/commits/131dc0aafb47ec55412c071f1e15137d2f0ccbb0), [de3f270](https://github.com/hansung-PreCaps/Backend/pull/20/commits/de3f2702765074cd84ca7f0d2f23c817577bcfe5), [5ec0fc6](https://github.com/hansung-PreCaps/Backend/pull/20/commits/5ec0fc6c0b78f3a26157f37db5931169c17616e3), [1380268](https://github.com/hansung-PreCaps/Backend/pull/20/commits/1380268941b62c587eaee215dae2a93a40dd05dd) 

@Enble 
자잘한 수정요청 적용했습니다

2024-10-29 07:10 UTC, lsh1215 commented
[5af3462](https://github.com/hansung-PreCaps/Backend/pull/20/commits/5af346223956272051d1a248019427de4b1875e4)

![image](https://github.com/user-attachments/assets/48102e2a-a11f-4ff8-a78a-5c656f343cfe)

@Enble 
login 할 때 refreshToken을 주는 방식이 맞더라구요. 그래서 로직 변경하고, refresh도 accessToken만 변경하는 것과 모두 변경하는 두 버전으로 만들었습니다(controller에는 하나만 적용)

2024-10-29 07:11 UTC, lsh1215 commented on src/main/java/com/pictalk/user/converter/UserConverter.java
> +
private으로 변경이 안되더라구요

2024-10-29 07:36 UTC, Enble commented
> [5af3462](https://github.com/hansung-PreCaps/Backend/pull/20/commits/5af346223956272051d1a248019427de4b1875e4)
> 
> ![image](https://private-user-images.githubusercontent.com/75378429/381016818-48102e2a-a11f-4ff8-a78a-5c656f343cfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODc1MDQsIm5iZiI6MTczMDE4NzIwNCwicGF0aCI6Ii83NTM3ODQyOS8zODEwMTY4MTgtNDgxMDJlMmEtYTExZi00ZmY4LWE3OGEtNWM2NTZmMzQzY2ZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA3MzMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhY2Y1ZmFkMGE3NmMzYjAxNTI5ZGI4NTM4ZmI5OTk2ODNhODZmNjE5NWQ0NWM0NWM1MzNkZWI1ZmJhMjUzYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O9R547EF46rQkRllR5_FLLeGCCDa1rIvEdUhTpHKYvc)
> 
> @Enble login 할 때 refreshToken을 주는 방식이 맞더라구요. 그래서 로직 변경하고, refresh도 accessToken만 변경하는 것과 모두 변경하는 두 버전으로 만들었습니다(controller에는 하나만 적용)

사실 refresh token을 주는 방식과 안주는 방식 모두 사용할 수 있습니다. refresh가 처음 나온 의도는 refresh로 access를 다시 발급받으라는 의도였지만, refresh를 외부에 노출시키는 위험성이 인지되고 나서부터는 refresh를 서버 안으로 숨기는 방식으로 변형되었다고 알고 있습니다. 또한 그러한 refresh 만료 처리를 위해 redis에 저장하는 방식 등이 고안되었습니다.
참고 바랍니다.

2024-10-29 07:39 UTC, Enble commented on src/main/java/com/pictalk/user/service/MyUserDetailsService.java
> -        return new org.springframework.security.core.userdetails.User(user.getUsername(), user.getPassword(), new ArrayList<>());
`ArrayList`는 컬렉션입니다. array가 아니에요. 참고해주세용

2024-10-29 07:42 UTC, Enble commented on src/main/java/com/pictalk/global/config/SecurityConfig.java
> +                                "/users/logout",
refresh와 logout을 permit한 의도는 무엇인가요?

2024-10-29 07:46 UTC, lsh1215 commented on src/main/java/com/pictalk/user/service/MyUserDetailsService.java
> -        return new org.springframework.security.core.userdetails.User(user.getUsername(), user.getPassword(), new ArrayList<>());
아 ArrayList 였네요. Array로 봐따...
![image](https://github.com/user-attachments/assets/5d2903bb-30ce-46cb-9f60-791f5cd76b2c)
요거 적용할려고 한건데 의미가 없네

![image](https://github.com/user-attachments/assets/d472f964-014a-4510-8958-ccea84d05786)
그래도 하는게 괜찮기는 한거 같다

2024-10-29 07:48 UTC, lsh1215 commented on src/main/java/com/pictalk/global/config/SecurityConfig.java
> +                                "/users/logout",
요거가 로직상 refresh는 accessToken 만료 시 재발급을 위해 사용하는거라 accessToken이 만료됐을 때 저걸 안 열어두면 security에서 막히더라구요. 그래서 열어둔거고 logout는 마찬가지기도 하고 쟤는 accessToken이 없어도 상관 없지않나 했습니다

2024-10-29 07:53 UTC, Enble commented on src/main/java/com/pictalk/global/jwt/JwtService.java
> +    public String reIssueRefreshToken(User user) {
저는 refresh token을 reissue하는 것이 하나의 단위기능이라고 생각합니다.
그래서 transaction을 부여하는 것이 필요하다고 생각하는데 의견이 궁금합니다.

2024-10-29 07:54 UTC, Enble approved these changes
고생하셨습니다!
LGTM

2024-10-29 08:14 UTC, merged

2024-10-29 08:15 UTC, lsh1215 commented on src/main/java/com/pictalk/global/jwt/JwtService.java
> +    public String reIssueRefreshToken(User user) {
음 이거는 형이 준 자료로 찾아보고 이후에 적용이 필요하면 적용해보겠습니다