[feat] 문자 전송 API 1차 구현 완료
hansung-PreCaps/Backend pull request #31
Opened 2024-11-06 19:14 UTC by rokaf6444

## 변경 사항

문자 전송 API (POST /api/messages/send)
- 문자 메시지를 전송하는 기능을 구현했습니다.
- MessageService의 sendSms 메서드에서 실제 SMS 전송 로직은 아직 구현이 필요합니다.

문자 리스트 조회 API (GET /api/messages)
- 전송된 문자 메시지의 리스트를 조회하는 기능을 구현했습니다.

문자 상세 조회 API (GET /api/messages/{message_id})
- 특정 메시지의 상세 정보를 조회하는 기능을 구현했습니다.

문자 예약 전송 취소 API (PATCH /api/messages/{message_id})
- 예약된 문자 메시지의 전송을 취소하는 기능을 구현했습니다.

문자 삭제 API (DELETE /api/messages/{message_id})
- 문자 메시지를 삭제하는 기능을 구현했습니다.

## 테스트 실행

- [x] 👍 Yes
- [ ] 🙅 No, Because they are not neaded
- [ ] 🤯 No, Because I needed help with writing tests

### 테스트 결과

<img width="700" alt="image" src="https://github.com/user-attachments/assets/7c0691a0-46a6-43da-9fda-0f3e2833ff28">
<img width="700" alt="image" src="https://github.com/user-attachments/assets/182e2de6-1faf-4326-b72f-6d92912d6320">

---

<img width="700" alt="image" src="https://github.com/user-attachments/assets/91c9e9c4-9167-4e0a-8170-d55487607a68">
<img width="700" alt="image" src="https://github.com/user-attachments/assets/0b47b066-741f-4880-969f-b60505b58c8d">

---

<img width="700" alt="image" src="https://github.com/user-attachments/assets/f6324eab-f747-4466-856b-6e0199cb816d">
<img width="700" alt="image" src="https://github.com/user-attachments/assets/b2c7a92e-9fd5-4992-8165-76ff0143b793">

---

<img width="700" alt="image" src="https://github.com/user-attachments/assets/d6609984-e777-4aa3-af66-63296aa402c2">
<img width="700" alt="image" src="https://github.com/user-attachments/assets/8d093960-5767-4a39-b054-c5ff9fe1f120">

---

<img width="700" alt="image" src="https://github.com/user-attachments/assets/8e416524-48fa-4f81-b606-ad11f423b954">
<img width="700" alt="image" src="https://github.com/user-attachments/assets/b7d8ba11-189d-4cad-a22a-75f4966db1d3">

## +α Checklist
- [ ] 자바 코드 컨벤션을 지키면서 프로그래밍했는가?
- [ ] 한 메서드에 오직 한 단계의 들여쓰기(indent)만 허용했는가?
- [ ] else 예약어를 쓰지 않았는가?
- [ ] 3개 이상의 인스턴스 변수를 가진 클래스를 구현하지 않았는가? (가능하면 인스턴스 변수의 수를 줄이기 위해 노력한다.)
- [ ] setter 없이 구현했는가?
- [ ] 메소드의 인자 수를 제한했는가? (4개 이상의 인자는 허용하지 않는다. 3개도 가능하면 줄이기 위해 노력해 본다.)
- [ ] 코드 한 줄에 점(.)을 하나만 허용했는가?
- [ ] 메소드가 한가지 일만 담당하도록 구현했는가?
- [ ] 클래스를 작게 유지하기 위해 노력했는가?

2024-11-06 19:44 UTC, lsh1215 commented on src/main/java/com/pictalk/message/dto/MessageDto.java
> +    @AllArgsConstructor
Lombok이 남발한 것처럼 느껴짐. 과연 다 필요할까?

2024-11-06 19:46 UTC, lsh1215 commented on src/main/java/com/pictalk/message/dto/MessageDto.java
> +        private String status;
snake case 와 camel case를 어디서는 camel 어디서는 snake을 사용 -> 통일 필요(통일은 camel로)

2024-11-06 19:46 UTC, lsh1215 commented on src/main/java/com/pictalk/message/dto/MessageDto.java
> +        private Long message_id;
이런곳도 마찬가지

2024-11-06 19:49 UTC, lsh1215 reviewed
MessageService에서 과연 이렇게 로직을 짰을 때 sender를 만들고 message를 만들었는데 receiver를 만드는 로직에서 실패했다면, table에 sender나 receiver는 저장되지 않을까?
혹은, 메시지를 생성하고 보내는 로직에서 객체는 생성했는데 보내는 로직에서 실패했다면, 메시지는 생성되지 않을까? -> 생성되지 않아야 맞을텐데?

즉, 트랜잭션 관리가 안되고 있거나 이후에 관리가 안되는 상황임. 

해결방법은?(생각보다 간단)

2024-11-08 02:53 UTC, rokaf6444 commented
ac35ed0e04256ee0431c053e07a989f200adba50: 변수 및 메서드 네이밍 일관성 유지 완료했습니다.

2024-11-08 02:54 UTC, rokaf6444 commented
9f8c45bfa50bf02a7808b00a86676b975e0addd5: MessageDto를 MessageRequestDto 및 MessageResponseDto로 분리 완료했습니다.

2024-11-08 04:16 UTC, rokaf6444 commented on src/main/java/com/pictalk/message/dto/MessageDto.java
> +        private String status;
확인했습니다.

2024-11-08 04:17 UTC, rokaf6444 commented on src/main/java/com/pictalk/message/dto/MessageDto.java
> +        private Long message_id;
확인했습니다.

2024-11-08 05:05 UTC, rokaf6444 commented
676fbdb99c45641139f17051aa12e858084ef0c3: 도메인 클래스 변수 보완 및 접근 메서드 수정 완료했습니다.

2024-11-08 05:32 UTC, Enble requested changes
리뷰입니다.

2024-11-08 05:32 UTC, Enble commented on src/main/java/com/pictalk/message/controller/MessageController.java
> +    public CommonResponse<SendMessageResponse> sendMessage(@Valid @RequestBody SendMessageRequest request) {
제가 알려드린 방식으로 user를 가져와서, `User` 엔티티와 연관관계 설정을 해주세요.
엔티티에 연관관계 메서드를 추가해도 괜찮을 것 같습니다.

2024-11-08 05:32 UTC, Enble commented on src/main/java/com/pictalk/message/controller/MessageController.java
> +    public CommonResponse<List<MessageResponse>> getMessages() {
해당  api를 왜 만드는지 생각해보세요. 분명 모든 유저의 메시지들을 조회하는 것이 아닌, 특정 유저의 모든 메시지들을 조회하는 기능일 겁니다.
알맞게 수정해주세요.

2024-11-08 06:24 UTC, rokaf6444 commented
80582c7147379debdaad59abab9a78a4b550cb17: MessageService 트랜잭션 적용 완료했습니다.

2024-11-08 07:34 UTC, rokaf6444 commented
3747366df3d7d675b5f17318b5752bdc5a037880: Lombok 임포트 구체화 완료했습니다.

2024-11-08 07:47 UTC, rokaf6444 commented on src/main/java/com/pictalk/message/dto/MessageDto.java
> +    @AllArgsConstructor
확인했습니다.

2024-11-08 07:52 UTC, rokaf6444 commented on src/main/java/com/pictalk/message/dto/MessageDto.java
> +    @AllArgsConstructor
현재 제 실력으로는 발생할 수 있는 문제와 고려해야 할 부분이 많아, 우선은 현 상태를 유지하겠습니다.

2024-11-09 10:20 UTC, rokaf6444 commented
22eca98d708fc696a7c2b81956da21adc413ad55: 'feat/25' 브랜치와 'origin/develop' 브랜치 간 충돌 해결 완료했습니다.

2024-11-09 21:41 UTC, rokaf6444 commented on src/main/java/com/pictalk/message/controller/MessageController.java
> +    public CommonResponse<SendMessageResponse> sendMessage(@Valid @RequestBody SendMessageRequest request) {
확인했습니다.

2024-11-09 21:42 UTC, rokaf6444 commented on src/main/java/com/pictalk/message/controller/MessageController.java
> +    public CommonResponse<List<MessageResponse>> getMessages() {
확인했습니다.

2024-11-09 21:46 UTC, rokaf6444 commented
bf6de6eadb9178c562092a1df858e6d50b7a5008: 인증 기반 메시지 관리 및 예약 취소 기능 개선 완료했습니다.

2024-11-10 02:18 UTC, Enble commented on src/main/java/com/pictalk/message/service/MessageService.java
> +        MessageStatus status = sendTime.isAfter(LocalDateTime.now()) ? MessageStatus.SCHEDULED : MessageStatus.SENT;
예약 전송을 구현하신 건지, 만약 그게 맞다면 어떻게 사용되는 로직인지 설명해주세요

2024-11-10 02:19 UTC, Enble commented on src/main/java/com/pictalk/message/service/MessageService.java
> +                .build();
나중에 모든 entity -> dto 변환, 혹은 dto -> entity 변환은 별도의 메서드나 converter를 통해 변환하도록 리펙토링해주세요

2024-11-10 05:55 UTC, rokaf6444 commented on src/main/java/com/pictalk/message/service/MessageService.java
> +        MessageStatus status = sendTime.isAfter(LocalDateTime.now()) ? MessageStatus.SCHEDULED : MessageStatus.SENT;
예약 전송을 구현했습니다. 제가 의도한 로직은, 현재 시간보다 미래 시간을 입력했을 때 문자가 예약 상태로 뜨게 하려는 것입니다. 생각해 보니까 이러한 상태면 매번 문자 보낼 때마다 시간을 입력해야 하고, 그때 시간을 과거 시간으로 입력하면 그 시간에 전송된 문자라고 떠서 관리가 안 되겠네요. 이 부분은 바로 수정해 두면 될까요?

2024-11-10 05:57 UTC, rokaf6444 commented on src/main/java/com/pictalk/message/service/MessageService.java
> +                .build();
확인했습니다.

2024-11-10 06:00 UTC, Enble commented on src/main/java/com/pictalk/message/service/MessageService.java
> +        MessageStatus status = sendTime.isAfter(LocalDateTime.now()) ? MessageStatus.SCHEDULED : MessageStatus.SENT;
예약 로직은 별도의 기술이 사용되어야 할 것으로 보입니다. 일단 논리적 에러가 있는 부분만 수정해서 커밋하고, 예약 로직은 다음 pr에서 완성하시죠

2024-11-10 06:06 UTC, rokaf6444 commented on src/main/java/com/pictalk/message/service/MessageService.java
> +        MessageStatus status = sendTime.isAfter(LocalDateTime.now()) ? MessageStatus.SCHEDULED : MessageStatus.SENT;
확인했습니다. 감사합니다.

2024-11-10 13:14 UTC, rokaf6444 commented
fabccf30cb3201fb96b113fe62780b8bdb6455e6: 즉시 발송과 예약 발송 로직 분리 완료했습니다.

2024-11-10 13:21 UTC, Enble commented
좋습니다!
LGTM

2024-11-10 13:21 UTC, Enble approved these changes
좋습니다!
LGTM

2024-11-10 13:30 UTC, merged